-- Only run in a disposable, migrated database AFTER infra/neon/database-roles.sql.
\set ON_ERROR_STOP on
BEGIN;
CREATE TABLE public.hosted_privilege_probe (id bigint GENERATED BY DEFAULT AS IDENTITY);
DO $$
BEGIN
  IF NOT has_table_privilege('sportsball_web', 'public.games', 'SELECT')
     OR has_table_privilege('sportsball_web', 'public.games', 'INSERT')
     OR has_table_privilege('sportsball_web', 'public.source_payloads', 'SELECT')
     OR has_table_privilege('sportsball_web', 'public.source_artifacts', 'SELECT')
     OR has_schema_privilege('sportsball_ingestion', 'public', 'CREATE')
     OR has_table_privilege('sportsball_backup', 'public.games', 'DELETE')
     OR NOT has_table_privilege('sportsball_backup', 'public.source_artifacts', 'SELECT')
     OR NOT has_table_privilege('sportsball_ingestion', 'public.hosted_privilege_probe', 'INSERT')
     OR NOT has_table_privilege('sportsball_backup', 'public.hosted_privilege_probe', 'SELECT')
     OR has_table_privilege('sportsball_web', 'public.hosted_privilege_probe', 'SELECT') THEN
    RAISE EXCEPTION 'Hosted database role isolation failed';
  END IF;
END $$;
SET LOCAL ROLE sportsball_ingestion;
INSERT INTO public.hosted_privilege_probe DEFAULT VALUES;
RESET ROLE;
SET LOCAL ROLE sportsball_backup;
SELECT count(*) FROM public.hosted_privilege_probe;
RESET ROLE;
ROLLBACK;
