const METRIC_DEFINITIONS: Record<string, string> = {
  Rank: "Current rank in the selected league, conference, or division view.",
  GP: "Games played in the selected season, phase, and filter context.",
  GS: "Games started by the goalie.",
  G: "Goals scored.",
  A: "Assists recorded.",
  PTS: "Points: goals plus assists for players, or standings points for teams.",
  W: "Wins.",
  L: "Losses.",
  OT: "Standings losses decided in overtime or a shootout.",
  OTL: "Overtime or shootout losses.",
  RW: "Regulation wins, excluding overtime and shootout wins.",
  DIFF: "Goal differential: goals scored minus goals allowed.",
  "+/-": "Plus-minus while the player was on the ice for eligible goals.",
  PIM: "Penalty minutes.",
  S: "Shots on goal.",
  SV: "Saves made by the goalie.",
  "SV%": "Save percentage: saves divided by shots on goal faced.",
  Teams: "Number of teams the player appeared for in the selected season.",
  Pos: "Player position.",
  Round: "Draft round in which the player was selected.",
  Overall: "Overall selection number in the draft.",
  TOI: "Total time on ice in the selected situation.",
  "xG%":
    "Expected-goal share: expected goals for divided by expected goals for and against. Above 50% means more shot quality than the opponent.",
  "CF%":
    "Corsi share: the percentage of all shot attempts taken by the selected team or player's team.",
  "FF%":
    "Fenwick share: the percentage of unblocked shot attempts taken by the selected team or player's team.",
  xGF: "Expected goals created from the quality and location of unblocked shots.",
  xGA: "Expected goals allowed based on the quality and location of unblocked shots faced.",
  GF: "Goals scored.",
  GA: "Goals allowed.",
  "Game score":
    "MoneyPuck's combined estimate of a player's contribution using scoring, shots, penalties, and defensive events.",
  ixG: "Individual expected goals generated by a skater's own unblocked shots.",
  Goals: "Goals scored by the player.",
  Points: "Goals plus assists recorded by the player.",
  GSAx: "Goals saved above expected: expected goals against minus actual goals allowed. Positive is better.",
  "Expected SOG": "Expected shots on goal based on the shots and chance quality faced.",
  SOG: "Shots on goal.",
  SA: "Shots on goal allowed.",
};

export function metricDefinition(label: string): string | undefined {
  return METRIC_DEFINITIONS[label];
}
